import exceptions

exceptions.open_file_for_reading('myfile.data')